/**
 * Stable client contract. `code` is what a client branches on, so a value here
 * is permanent once shipped; the human-readable `detail` is free to change
 * (docs/rules/06-api-design.md C3).
 */
export const ERROR_CODES = {
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  CSRF_VALIDATION_FAILED: 'CSRF_VALIDATION_FAILED',
  FORBIDDEN: 'FORBIDDEN',
  ACCESS_CONTEXT_REQUIRED: 'ACCESS_CONTEXT_REQUIRED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
  REFERENCE_CONSTRAINT: 'REFERENCE_CONSTRAINT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  UPSTREAM_TIMEOUT: 'UPSTREAM_TIMEOUT',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** RFC 9457 `type` is a URI; the code is its last segment. */
export const ERROR_TYPE_BASE_URI = 'https://api.boilerplate.com/errors/';
